In [248]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [249]:
data = pd.read_csv("TRAIN.csv")
data

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,S1,L3,R1,2018-01-01,1,Yes,9,7011.84
1,T1000002,253,S4,L2,R1,2018-01-01,1,Yes,60,51789.12
2,T1000003,252,S3,L2,R1,2018-01-01,1,Yes,42,36868.20
3,T1000004,251,S2,L3,R1,2018-01-01,1,Yes,23,19715.16
4,T1000005,250,S2,L3,R4,2018-01-01,1,Yes,62,45614.52
...,...,...,...,...,...,...,...,...,...,...
188335,T1188336,149,S2,L3,R2,2019-05-31,1,Yes,51,37272.00
188336,T1188337,153,S4,L2,R1,2019-05-31,1,No,90,54572.64
188337,T1188338,154,S1,L3,R2,2019-05-31,1,No,56,31624.56
188338,T1188339,155,S3,L1,R2,2019-05-31,1,Yes,70,49162.41
188339,T1188340,152,S2,L1,R1,2019-05-31,1,No,47,37977.00

In [250]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188340 entries, 0 to 188339
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ID             188340 non-null  object
 1   Store_id       188340 non-null  int64
 2   Store_Type     188340 non-null  object
 3   Location_Type  188340 non-null  object
 4   Region_Code    188340 non-null  object
 5   Date           188340 non-null  object
 6   Holiday        188340 non-null  int64
 7   Discount       188340 non-null  object
 8   #Order         188340 non-null  int64
 9   Sales          188340 non-null  float64
dtypes: float64(1), int64(3), object(6)
memory usage: 14.4+ MB

In [251]:
data.isnull().sum()

ID               0
Store_id         0
Store_Type       0
Location_Type    0
Region_Code      0
Date             0
Holiday          0
Discount         0
#Order           0
Sales            0
dtype: int64

In [252]:
data.describe()

            Store_id        Holiday         #Order          Sales
count  188340.000000  188340.000000  188340.000000  188340.000000
mean      183.000000       0.131783      68.205692   42784.327982
std       105.366308       0.338256      30.467415   18456.708302
min         1.000000       0.000000       0.000000       0.000000
25%        92.000000       0.000000      48.000000   30426.000000
50%       183.000000       0.000000      63.000000   39678.000000
75%       274.000000       0.000000      82.000000   51909.000000
max       365.000000       1.000000     371.000000  247215.000000

In [253]:
import plotly.express as px

In [254]:
pie1 = data["Store_Type"].value_counts()
store = pie1.index
orders1 = pie1.values

fig = px.pie(pie1, values=orders1, names=store)
fig.show()

In [255]:
pie2 = data["Location_Type"].value_counts()
location = pie2.index
orders2 = pie2.values

fig = px.pie(pie2, values = orders2, names=location)
fig.show()

In [256]:
pie3 = data["Region_Code"].value_counts()
region = pie3.index
orders3 = pie3.values

fig = px.pie(pie3, values = orders3, names=region)
fig.show()

In [257]:
pie4 = data["Discount"].value_counts()
discount = pie4.index
orders4 = pie4.values

fig = px.pie(pie4, values = orders4, names=discount)
fig.show()

In [258]:
pie5 = data["Holiday"].value_counts()
holiday = pie5.index
orders5 = pie5.values

fig = px.pie(pie5, values = orders5, names=holiday)
fig.show()

In [259]:
data["Discount"] = data["Discount"].map({"Yes": 1, "No": 0})
data["Store_Type"] = data["Store_Type"].map({"S1": 1, "S2": 2, "S3": 3, "S4": 4})
data["Location_Type"] = data["Location_Type"].map({"L1": 1, "L2": 2, "L3": 3, "L4": 4, "L5": 5})
data["Region_Code"] = data["Region_Code"].map({"R1": 1, "R2": 2, "R3": 3, "R4": 4})

data

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,1,3,1,2018-01-01,1,1,9,7011.84
1,T1000002,253,4,2,1,2018-01-01,1,1,60,51789.12
2,T1000003,252,3,2,1,2018-01-01,1,1,42,36868.20
3,T1000004,251,2,3,1,2018-01-01,1,1,23,19715.16
4,T1000005,250,2,3,4,2018-01-01,1,1,62,45614.52
...,...,...,...,...,...,...,...,...,...,...
188335,T1188336,149,2,3,2,2019-05-31,1,1,51,37272.00
188336,T1188337,153,4,2,1,2019-05-31,1,0,90,54572.64
188337,T1188338,154,1,3,2,2019-05-31,1,0,56,31624.56
188338,T1188339,155,3,1,2,2019-05-31,1,1,70,49162.41
188339,T1188340,152,2,1,1,2019-05-31,1,0,47,37977.00

In [260]:
data.drop(columns={"ID", "Region_Code", "Date"}, inplace=True)
data

,Store_id,Store_Type,Location_Type,Holiday,Discount,#Order,Sales
0,1,1,3,1,1,9,7011.84
1,253,4,2,1,1,60,51789.12
2,252,3,2,1,1,42,36868.20
3,251,2,3,1,1,23,19715.16
4,250,2,3,1,1,62,45614.52
...,...,...,...,...,...,...,...
188335,149,2,3,1,1,51,37272.00
188336,153,4,2,1,0,90,54572.64
188337,154,1,3,1,0,56,31624.56
188338,155,3,1,1,1,70,49162.41
188339,152,2,1,1,0,47,37977.00

In [261]:
X = data[["Store_Type", "Location_Type", "Holiday", "Discount"]]
y = pd.Series(data["#Order"])

In [262]:
X

        Store_Type  Location_Type  Holiday  Discount
0                1              3        1         1
1                4              2        1         1
2                3              2        1         1
3                2              3        1         1
4                2              3        1         1
...            ...            ...      ...       ...
188335           2              3        1         1
188336           4              2        1         0
188337           1              3        1         0
188338           3              1        1         1
188339           2              1        1         0

[188340 rows x 4 columns]

In [263]:
y

0          9
1         60
2         42
3         23
4         62
          ..
188335    51
188336    90
188337    56
188338    70
188339    47
Name: #Order, Length: 188340, dtype: int64

In [264]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [265]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [266]:
import lightgbm as ltb
model = ltb.LGBMRegressor()

In [267]:
model.fit(X_train_scaled, y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001749 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 17
[LightGBM] [Info] Number of data points in the train set: 150672, number of used features: 4
[LightGBM] [Info] Start training from score 68.163401

LGBMRegressor()

In [268]:
y_pred = model.predict(X_test_scaled)

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning:

X does not have valid feature names, but LGBMRegressor was fitted with feature names

In [269]:
from sklearn.metrics import mean_absolute_percentage_error, r2_score

In [270]:
r2_score(y_test, y_pred)

0.592140392819931

In [271]:
data = pd.DataFrame(data={"Predicted Orders": y_pred.flatten()})

In [272]:
data

       Predicted Orders
0             47.351897
1             97.068717
2             66.577788
3             85.143083
4             54.451098
...                 ...
37663         66.577788
37664         47.722874
37665         47.351897
37666         61.749386
37667         85.341039

[37668 rows x 1 columns]